get http://localhost:5000

###

post http://localhost:5000/auth/register
Content-Type: application/json

{
  "password": "test",
  "name": "test",
  "email": "a@gmail.com"
}

###
post http://localhost:5000/auth/login
Content-Type: application/json

{
  "email": "a@gmail.com",
  "password": "test"    
}

###
post http://localhost:5000/data/addcategory
Content-Type: application/json

{
  "name": "Science",
  "subcategory": ["Physics", "Chemistry", "Biology"]
}


###
get http://localhost:5000/data/getcategories


// get all users
// add token in header
###
get http://localhost:5000/users/all 
Content-Type: application/json
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZDA2OTlmZWNhYjk4YTVmNGM3ZjU3MiIsImVtYWlsIjoiYUBnbWFpbC5jb20iLCJuYW1lIjoiUmViZWthaCBNaWthZWxzb24iLCJpYXQiOjE2OTE2MDg3Mjl9.G_c7u7j1dzAZM8dftNvI9Jo0A1_s9FMchrOHGh4yaMg

###
delete http://localhost:5000/data/deleteall
Content-Type: application/json
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZTMxMGFjOWVkM2YyMTk3MDhhOGRjOCIsImVtYWlsIjoiYnVja3lAZ21haWwuY29tIiwibmFtZSI6IkJ1Y2t5IFJvYmVydHMiLCJpYXQiOjE2OTI2MDI1NDl9.4aVBCnbMYiDAxrUKdLmOBKoKgl7t_k2ew38Wbw1utjc

###
get http://localhost:5000/users/getuser
Content-Type: application/json
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZGY4ODBkZjlmZjE3Y2E5NjEwMzljNiIsImVtYWlsIjoicmViZWthaEBnbWFpbC5jb20iLCJuYW1lIjoiUmViZWthaCBNaWthZWxzb24iLCJpYXQiOjE2OTIzNzA5ODZ9.1Mvbf4IQs0qWw2FAmN7WZfhMz3lbxtePFUsz5yel4So

###
post http://localhost:5000/data/create-payment-sesson
Content-Type: application/json
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZTM0N2MxN2U2MTQ3NzhiYjY3NGI5OSIsImVtYWlsIjoibWFoYnViQGdtYWlsLmNvbSIsIm5hbWUiOiJNYWhidWJ1bCBIYXF1ZSIsImlhdCI6MTY5MjYxNjc2Mn0.lQI8tYyRepbWx0o3Wu2WCoXdbEmrlDCh3wErulzfoiQ

{
    "courseId": "64e3111a9ed3f219708a8de7"
}

###
put http://localhost:5000/users/follow/64e326469ed3f219708a8f41
Content-Type: application/json
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZTMxMTBiOWVkM2YyMTk3MDhhOGRkOSIsImVtYWlsIjoiYnVja3lAZ21haWwuY29tIiwibmFtZSI6IkJ1Y2t5IFJvYmVydHMiLCJpYXQiOjE2OTk4MDkxODN9.sKzO1anqdNsVLEX8JcSlcT9IulHpePAS2aKULFCfggQ
